os:
  - linux

language:
  - python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - find . | grep -E "\.py$" | xargs python -m compileall

cache:
  - pip

notifications:
  email:
    - false