os:
  - linux

language:
  - python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - find . | grep -E "\.py$" | xargs python -m compileall
  - find . | grep -E "\.py$" | xargs flake8 --max-line-length 120

cache:
  - pip

notifications:
  email:
    - false