name: Lint and compile
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8']
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install build and lint dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install flake8
      - name: Lint (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: python3 -m flake8
      - name: Lint (Windows)
        if: matrix.os == 'windows-latest'
        run: python -m flake8
      - name: Compile (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: python3 -m compileall .
        working-directory: ./suprkewl-bot
      - name: Compile (Windows)
        if: matrix.os == 'windows-latest'
        run: python -m compileall .
        working-directory: ./suprkewl-bot
